# Generated by Django 5.0.6 on 2024-07-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
    ]
