# Generated by Django 5.0.6 on 2024-07-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0005_workerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='Worker_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
