# Generated by Django 5.0.6 on 2024-08-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0006_alter_workerdetails_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='Worker_image',
            field=models.ImageField(blank=True, default='images/propic.jpeg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='Working_areas',
            field=models.ManyToManyField(related_name='areas', to='formsapp.workerarea'),
        ),
    ]
